CREATE TABLE tbl_note_tags
(
	id INT NOT NULL AUTO_INCREMENT,
    note_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (note_id) REFERENCES tbl_notes(id) 
		ON DELETE CASCADE 
    	ON UPDATE CASCADE,
   	FOREIGN KEY (tag_id) REFERENCES tbl_tags(id) 
		ON DELETE CASCADE
    	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;